# Generated by Django 6.0.2 on 2026-02-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotFoydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('ism', models.CharField(blank=True, max_length=200, verbose_name='Ism')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('so_rovlar_soni', models.IntegerField(default=0, verbose_name="So'rovlar soni")),
                ('birinchi_murojaat', models.DateTimeField(auto_now_add=True, verbose_name='Birinchi murojaat')),
                ('oxirgi_murojaat', models.DateTimeField(auto_now=True, verbose_name='Oxirgi murojaat')),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchi',
                'verbose_name_plural': 'Bot foydalanuvchilar',
                'ordering': ['-oxirgi_murojaat'],
            },
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='excel_files/', verbose_name='Excel fayl')),
                ('yuklangan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('yozuvlar_soni', models.IntegerField(default=0, verbose_name='Yozuvlar soni')),
                ('izoh', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Excel fayl',
                'verbose_name_plural': 'Excel fayllar',
                'ordering': ['-yuklangan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='KadastrMalumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=200, verbose_name='Viloyat')),
                ('tuman', models.CharField(max_length=200, verbose_name='Tuman')),
                ('kadastr_raqami', models.CharField(db_index=True, max_length=200, verbose_name='Kadastr raqami')),
                ('invoys_raqami', models.CharField(blank=True, max_length=200, verbose_name='Invoys raqami')),
                ('summa_miqdori', models.CharField(blank=True, max_length=200, verbose_name="To'lov miqdori")),
                ('tolovchi_fio', models.CharField(blank=True, max_length=300, verbose_name="To'lovchi F.I.O")),
                ('tolov_holati', models.CharField(blank=True, max_length=100, verbose_name="To'lov holati")),
                ('excel_fayl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malumatlar', to='kadastr_app.excelupload', verbose_name='Manba fayl')),
            ],
            options={
                'verbose_name': "Kadastr ma'lumot",
                'verbose_name_plural': "Kadastr ma'lumotlar",
            },
        ),
    ]
