# Generated by Django 6.0.2 on 2026-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadastrmalumat',
            name='kocha',
            field=models.CharField(default=1, max_length=200, verbose_name="Ko'\\cha nomi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kadastrmalumat',
            name='mfy',
            field=models.CharField(default=1, max_length=200, verbose_name='Mahalla nomi'),
            preserve_default=False,
        ),
    ]
