# Generated by Django 6.0.2 on 2026-02-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadastr_app', '0002_kadastrmalumat_kocha_kadastrmalumat_mfy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObyektExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='obyekt_excel/', verbose_name='Excel fayl')),
                ('yuklangan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('yozuvlar_soni', models.IntegerField(default=0, verbose_name='Yozuvlar soni')),
                ('izoh', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Excel fayl (Obyekt holati)',
                'verbose_name_plural': 'Excel fayllar (Obyekt holati)',
                'ordering': ['-yuklangan_vaqt'],
            },
        ),
        migrations.AlterModelOptions(
            name='excelupload',
            options={'ordering': ['-yuklangan_vaqt'], 'verbose_name': "Excel fayl (To'lov)", 'verbose_name_plural': "Excel fayllar (To'lov)"},
        ),
        migrations.AlterModelOptions(
            name='kadastrmalumat',
            options={'verbose_name': "Kadastr to'lov ma'lumot", 'verbose_name_plural': "Kadastr to'lov ma'lumotlar"},
        ),
        migrations.AlterField(
            model_name='kadastrmalumat',
            name='kocha',
            field=models.CharField(max_length=200, verbose_name="Ko'cha nomi"),
        ),
        migrations.CreateModel(
            name='ObyektMalumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadastr_raqami', models.CharField(db_index=True, max_length=200, verbose_name='Kadastr raqami')),
                ('viloyat', models.CharField(blank=True, max_length=200, verbose_name='Viloyat nomi')),
                ('tuman', models.CharField(blank=True, max_length=200, verbose_name='Tuman nomi')),
                ('mfy', models.CharField(blank=True, max_length=200, verbose_name='MFY')),
                ('holati', models.CharField(blank=True, max_length=200, verbose_name='Holati')),
                ('excel_fayl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malumatlar', to='kadastr_app.obyektexcelupload', verbose_name='Manba fayl')),
            ],
            options={
                'verbose_name': 'Obyekt holati',
                'verbose_name_plural': 'Obyekt holatlari',
            },
        ),
    ]
